# Generated by Django 6.0.6 on 2026-06-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('sender', models.EmailField(blank=True, max_length=255, null=True)),
                ('receiver', models.EmailField(blank=True, max_length=255, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('folder_path', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_received', '-date_sent'],
                'indexes': [models.Index(fields=['sender'], name='emails_emai_sender_a54e55_idx'), models.Index(fields=['date_received'], name='emails_emai_date_re_7ef2c4_idx')],
            },
        ),
    ]
